# Generated by Django 5.2.2 on 2025-06-07 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat_app', '0004_remove_message_room_id_message_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 22, 58, 32, 300602, tzinfo=datetime.timezone.utc)),
        ),
    ]
