# Generated by Django 5.2.2 on 2025-06-08 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat_app', '0006_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 8, 2, 43, 16, 645580, tzinfo=datetime.timezone.utc)),
        ),
    ]
