# Generated by Django 5.2.2 on 2025-06-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livechat_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='room_id',
        ),
    ]
