# Generated by Django 5.2.2 on 2025-06-07 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat_app', '0002_rename_room_message_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 18, 7, 35, 426082, tzinfo=datetime.timezone.utc)),
        ),
    ]
