# Generated by Django 5.2.2 on 2025-06-08 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat_app', '0005_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 8, 0, 40, 27, 166016, tzinfo=datetime.timezone.utc)),
        ),
    ]
